### ISSUE TITLE
Demo video on real hardware in readme

### ISSUE THREAD

**Issue by mightyiam** [hungtruong/TouchFart#5]

**Comment by hungtruong** [comment]
Buy me a new Macbook and I'd be happy to record a new demo! 😃

**Comment by mightyiam** [comment]
A cause worthy of a modern crowd funding campaign.

**Comment by LucaTNT** [comment]
I took one for the team and bought a new MBP just for the purpose of making [this video](https://youtu.be/VTSDHwMAyi4).

**Comment by mightyiam** [comment]
You done good, @LucaTNT . You done good.

**Comment by hungtruong** [comment]
I added this to the readme, thanks!
