### ISSUE TITLE
Add install instructions to README

### ISSUE THREAD

**Issue by jglovier** [hungtruong/TouchFart#9]
Could you add installation instructions to the README?

**Comment by josiah1888** [comment]
+1

My new Macbook needs to fart, but it can't figure out how

**Comment by jglovier** [comment]
FTR, I realize you can simply download the Xcode project and run it via Xcode, but it would be great to have an installer package setup and posted as a Release in the repo so that it can be run simply as an app, rather than an Xcode project.

**Comment by LucaTNT** [comment]
I compiled and signed the app, you can download it from [here](https://files.lucazorzi.net/TouchFart/).
@hungtruong, feel free to add it to the releases for this repo, if you'd like.

**Comment by hungtruong** [comment]
Whoa, thanks for doing that! I added it to the releases as 1.0 and uploaded the zip.
